# Build settings
url: http://www.josephbergdoll.com
markdown: kramdown
source: .
destination: ./_prod
layouts_dir: ./_layouts
includes_dir: ./_includes

gems:
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
